# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6bce6b128d5d19d33686b60d41c92824"
name = "scriberr"
handle = "scriberr"
application_url = "https://convention-fit-surprise-mechanical.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
# read_users scope is required to access staff member information
scopes = "write_products,read_users"

[auth]
redirect_urls = ["https://convention-fit-surprise-mechanical.trycloudflare.com/auth/callback", "https://convention-fit-surprise-mechanical.trycloudflare.com/auth/shopify/callback", "https://convention-fit-surprise-mechanical.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
