# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4444a58754e272c8a2aeba645e247b56"
name = "ScriberrDEV"
application_url = "https://scriberrdev.vercel.app"
embedded = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://scriberrdev.vercel.app/auth/callback",
  "https://scriberrdev.vercel.app/auth/shopify/callback", 
  "https://scriberrdev.vercel.app/api/auth/callback"
]

[build]
automatically_update_urls_on_dev = true
